#??? ??(Data Source)
spring:
  datasource:
    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      driver-class-name: org.h2.Driver
      driver-calss-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/jpa
      jdbc-url: jdbc:log4jdbc:h2:tcp://localhost/~/test
      username: sa
      password:
      idle-timeout: 10000

# Resource and Thymeleaf Refresh
  devtools.livereload.enabled: true
  thymeleaf.cache: false

# JPA Properties
  jpa:
    #database: mysql
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # ??
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true # hibernate.ddl-auto ????
    hibernate.ddl-auto: create # update/validate/create/create-drop/none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


